# ===========================
# TalentBridge Application Config
# ===========================

# Server
server.port=${PORT:8080}
# ===========================
# Database - MySQL
# ===========================
#spring.datasource.url=jdbc:mysql://localhost:3306/talentbridge?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=12345
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===========================
# Database - MySQL (Railway)
# ===========================
# [HOST], [PORT], [DATABASE_NAME]
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=ecyYbyIwmjBySdxPleiPzpsIzUlpDFpq

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.forward-headers-strategy=framework
# ===========================
# JPA / Hibernate
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# ===========================
# JWT Configuration
# ===========================
app.jwt.secret=dGFsZW50YnJpZGdlc2VjcmV0a2V5Zm9yandiYXNlNjRlbmNvZGVkc3RyaW5nMTIzNDU2Nzg5MA==
app.jwt.expiration-ms=86400000

# ===========================
# Logging
# ===========================
logging.level.com.demo.talentbridge=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG

# ===========================
# Jackson
# ===========================
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Asia/Ho_Chi_Minh

# ===== CLOUDINARY CONFIG =====
cloudinary.cloud-name=dzfgq2n19
cloudinary.api-key=922436613794848
cloudinary.api-secret=08Xv8-w4q0AH9IPY1PdpMhA5TKA
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB